VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsView"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'Private strViewName As String
'Private clsChild As clsView
'
'Private Sub Class_Initialize(ByVal strName As String)
'    strViewName = strName
'End Sub
'
'Public Property Get ViewName() As String
'    ViewName = strViewName
'End Property
'
'Public Property Get Child() As clsView
'    Child = clsChild
'End Property
'
'Public Property Let Child(clsNewChild As clsView)
'    clsChild = clsNewChild
'End Property
