'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class MyResources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RadioDld.MyResources", GetType(MyResources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property CSS_STYLES() As Byte()
        Get
            Dim obj As Object = ResourceManager.GetObject("CSS_STYLES", resourceCulture)
            Return CType(obj,Byte())
        End Get
    End Property
    
    Friend Shared ReadOnly Property fmt24_1() As Byte()
        Get
            Dim obj As Object = ResourceManager.GetObject("fmt24_1", resourceCulture)
            Return CType(obj,Byte())
        End Get
    End Property
    
    Friend Shared ReadOnly Property icoAPPICON() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("icoAPPICON", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to body { 
    '''	background-color: #3F3F3F;
    '''	font: 8pt verdana;
    '''	color: white;
    '''}
    '''
    '''html, body, table {
    '''	height: 100%;
    '''	margin: 0px;
    '''}
    '''
    '''h1 {
    '''	font-size: 10pt;
    '''	margin-bottom: 12px;
    '''	padding-left: 5px;
    '''}
    '''
    '''h2 {
    '''	color: #999999;
    '''	font-size: 8pt;
    '''	margin-top: 0px;
    '''	margin-bottom: 5px;
    '''}
    '''
    '''table {
    '''	width: 100%;
    '''	border-collapse: collapse;
    '''	margin: 0px;
    '''}
    '''
    '''td {
    '''	vertical-align: top;
    '''	margin: 0px;	
    '''}
    '''
    '''.maintd {
    '''	padding: 10px;
    '''}
    '''
    '''.bottomrow {
    '''	vertical-align: bottom;
    '''}
    '''
    '''.contentbox  [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property sidebar_css() As String
        Get
            Return ResourceManager.GetString("sidebar_css", resourceCulture)
        End Get
    End Property
End Class
