'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RadioDld.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property icon_error() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_error", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property icon_main() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_main", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property icon_main_img32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_main_img32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_main_img64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_main_img64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_working() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_working", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property list_converting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_converting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_downloaded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_downloaded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_downloaded_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_downloaded_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_downloading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_downloading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_subscribed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_subscribed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_waiting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_waiting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property provider_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("provider_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_clean_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_clean_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_current_episodes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_current_episodes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_options() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_options", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_report_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_report_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_retry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_retry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_subscribe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_subscribe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property toolbar_unsubscribe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("toolbar_unsubscribe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property views_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("views_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property views_downloads() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("views_downloads", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property views_find_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("views_find_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property views_forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("views_forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property views_subscriptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("views_subscriptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
