using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace RadioDld.My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioDld.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		static internal System.Drawing.Icon icon_error {
			get {
				object obj = ResourceManager.GetObject("icon_error", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		static internal System.Drawing.Icon icon_main {
			get {
				object obj = ResourceManager.GetObject("icon_main", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		static internal System.Drawing.Bitmap icon_main_img32 {
			get {
				object obj = ResourceManager.GetObject("icon_main_img32", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap icon_main_img64 {
			get {
				object obj = ResourceManager.GetObject("icon_main_img64", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Icon icon_working {
			get {
				object obj = ResourceManager.GetObject("icon_working", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		static internal System.Drawing.Bitmap list_converting {
			get {
				object obj = ResourceManager.GetObject("list_converting", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap list_downloaded {
			get {
				object obj = ResourceManager.GetObject("list_downloaded", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap list_downloaded_new {
			get {
				object obj = ResourceManager.GetObject("list_downloaded_new", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap list_downloading {
			get {
				object obj = ResourceManager.GetObject("list_downloading", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap list_error {
			get {
				object obj = ResourceManager.GetObject("list_error", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap list_favourite {
			get {
				object obj = ResourceManager.GetObject("list_favourite", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap list_subscribed {
			get {
				object obj = ResourceManager.GetObject("list_subscribed", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap list_waiting {
			get {
				object obj = ResourceManager.GetObject("list_waiting", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Icon overlay_downloading {
			get {
				object obj = ResourceManager.GetObject("overlay_downloading", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		static internal System.Drawing.Icon overlay_error {
			get {
				object obj = ResourceManager.GetObject("overlay_error", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		static internal System.Drawing.Bitmap provider_default {
			get {
				object obj = ResourceManager.GetObject("provider_default", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap search_close {
			get {
				object obj = ResourceManager.GetObject("search_close", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap search_close_hover {
			get {
				object obj = ResourceManager.GetObject("search_close_hover", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap search_close_pressed {
			get {
				object obj = ResourceManager.GetObject("search_close_pressed", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap search_icon {
			get {
				object obj = ResourceManager.GetObject("search_icon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_add_favourite {
			get {
				object obj = ResourceManager.GetObject("toolbar_add_favourite", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_choose_programme {
			get {
				object obj = ResourceManager.GetObject("toolbar_choose_programme", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_clean_up {
			get {
				object obj = ResourceManager.GetObject("toolbar_clean_up", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_current_episodes {
			get {
				object obj = ResourceManager.GetObject("toolbar_current_episodes", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_delete {
			get {
				object obj = ResourceManager.GetObject("toolbar_delete", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_download {
			get {
				object obj = ResourceManager.GetObject("toolbar_download", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_help {
			get {
				object obj = ResourceManager.GetObject("toolbar_help", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_options {
			get {
				object obj = ResourceManager.GetObject("toolbar_options", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_play {
			get {
				object obj = ResourceManager.GetObject("toolbar_play", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_remove_favourite {
			get {
				object obj = ResourceManager.GetObject("toolbar_remove_favourite", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_report_error {
			get {
				object obj = ResourceManager.GetObject("toolbar_report_error", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_retry {
			get {
				object obj = ResourceManager.GetObject("toolbar_retry", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_subscribe {
			get {
				object obj = ResourceManager.GetObject("toolbar_subscribe", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap toolbar_unsubscribe {
			get {
				object obj = ResourceManager.GetObject("toolbar_unsubscribe", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap views_back {
			get {
				object obj = ResourceManager.GetObject("views_back", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap views_downloads {
			get {
				object obj = ResourceManager.GetObject("views_downloads", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap views_favourites {
			get {
				object obj = ResourceManager.GetObject("views_favourites", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap views_find_new {
			get {
				object obj = ResourceManager.GetObject("views_find_new", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap views_forward {
			get {
				object obj = ResourceManager.GetObject("views_forward", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap views_subscriptions {
			get {
				object obj = ResourceManager.GetObject("views_subscriptions", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}
