---
name: CI
on:
  push:
    branches-ignore: dependabot/**
  pull_request:
  schedule:
    - cron: '30 12 * * 5'

permissions:
  contents: read

jobs:
  overcommit:
    name: Overcommit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and sign
        run: |
          sudo gem install overcommit --no-document
          overcommit --sign
          overcommit --sign pre-commit

      - name: Run hooks
        env:
          GIT_AUTHOR_NAME: Dummy
          GIT_AUTHOR_EMAIL: dummy@example.com
          SKIP: RSpec,RuboCop
        run: overcommit --run
