#!/bin/bash -e

# This file is part of Radio Downloader.
# Copyright © 2019 by the authors - see the AUTHORS file for details.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

cd "$(dirname "$0")"

version=$(git describe --abbrev=8)
version="${version//-g/-}"

description="An easy to use application for podcast subscriptions and downloads"
url="https://nerdoftheherd.com/tools/radiodld/"

chmod +x radio-downloader

fpm --input-type dir \
    --output-type pacman \
    --name radio-downloader \
    --version "${version//-/_}" \
    --architecture all \
    --depends mono --depends sqlite \
    --license GPL3 \
    --url "$url" \
    --description "$description" \
    --chdir .. \
    "bin/mono/Radio Downloader.exe=/usr/share/radio-downloader/" \
    "bin/mono/System.Data.SQLite.dll=/usr/share/radio-downloader/" \
    "bin/mono/PodcastProvider.dll=/usr/share/radio-downloader/" \
    "bin/mono/HtmlAgilityPack.dll=/usr/share/radio-downloader/" \
    "bin/mono/Microsoft.VisualBasic.dll=/usr/share/radio-downloader/" \
    "bin/mono/store.db=/usr/share/radio-downloader/" \
    "Resources/icons/Icon.png=/usr/share/pixmaps/radio-downloader.png" \
    "installer/radio-downloader.desktop=/usr/share/applications/" \
    "installer/radio-downloader=/usr/bin/"
