#!/bin/bash -e

# Copyright © 2019 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

cd "$(dirname "$0")"

version=$(git describe --abbrev=8)
version="${version//-g/-}"

common=(
    --name radio-downloader \
    --input-type dir \
    --architecture all \
    --license GPL3 \
    --url "https://nerdoftheherd.com/tools/radiodld/" \
    --description \
        "Easy to use application for podcast subscriptions and downloads" \
    --chdir .. \
    "bin/mono/Radio Downloader.exe=/usr/share/radio-downloader/" \
    "bin/mono/Radio Downloader.exe.config=/usr/share/radio-downloader/" \
    "bin/mono/System.Data.SQLite.dll=/usr/share/radio-downloader/" \
    "bin/mono/PodcastProvider.dll=/usr/share/radio-downloader/" \
    "bin/mono/HtmlAgilityPack.dll=/usr/share/radio-downloader/" \
    "bin/mono/Microsoft.VisualBasic.dll=/usr/share/radio-downloader/" \
    "bin/mono/store.db=/usr/share/radio-downloader/" \
    "Resources/icons/Icon.png=/usr/share/pixmaps/radio-downloader.png" \
    "installer/radio-downloader.desktop=/usr/share/applications/" \
    "installer/radio-downloader=/usr/bin/"
)

chmod +x radio-downloader

fpm --output-type pacman \
    --version "${version//-/_}" \
    --depends mono \
    --depends sqlite \
    "${common[@]}"

fpm --output-type deb \
    --name radio-downloader \
    --version "$version" \
    --depends libmono-system-web4.0-cil \
    --depends libmono-system-windows-forms4.0-cil \
    --depends libsqlite3-0 \
    "${common[@]}"
