#!/bin/bash -e

# This file is part of Radio Downloader.
# Copyright © 2019 by the authors - see the AUTHORS file for details.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

cd "$(dirname "$0")"

version=$(git describe --abbrev=8)
version="${version//-g/-}"

common=(
    --name radio-downloader \
    --input-type dir \
    --architecture all \
    --license GPL3 \
    --url "https://nerdoftheherd.com/tools/radiodld/" \
    --description \
        "Easy to use application for podcast subscriptions and downloads" \
    --chdir .. \
    "bin/mono/Radio Downloader.exe=/usr/share/radio-downloader/" \
    "bin/mono/Radio Downloader.exe.config=/usr/share/radio-downloader/" \
    "bin/mono/System.Data.SQLite.dll=/usr/share/radio-downloader/" \
    "bin/mono/PodcastProvider.dll=/usr/share/radio-downloader/" \
    "bin/mono/HtmlAgilityPack.dll=/usr/share/radio-downloader/" \
    "bin/mono/Microsoft.VisualBasic.dll=/usr/share/radio-downloader/" \
    "bin/mono/store.db=/usr/share/radio-downloader/" \
    "Resources/icons/Icon.png=/usr/share/pixmaps/radio-downloader.png" \
    "installer/radio-downloader.desktop=/usr/share/applications/" \
    "installer/radio-downloader=/usr/bin/"
)

chmod +x radio-downloader

fpm --output-type pacman \
    --version "${version//-/_}" \
    --depends mono \
    --depends sqlite \
    "${common[@]}"

fpm --output-type deb \
    --name radio-downloader \
    --version "$version" \
    --depends libmono-system-windows-forms4.0-cil \
    --depends libsqlite3-0 \
    "${common[@]}"
